function ManageServicesParams(){
    $Script:nTimeStop = [int]60
    $Script:nTimeStart= [int]10
    
    $Local:aSvrLst= @()
    $Local:cSrvApp= '192.168.80.10'
    $Local:cSrvJob= '192.168.80.18'
    $Local:cSrvAdt= '192.168.80.12'
    $Local:cSrvLic= '192.168.80.10'
    $Local:cSrvTss= '192.168.80.27'
    $Local:cSrvDba= '192.168.80.10'
    $Local:cSrvPrt= '192.168.80.29'

    return $aSvrLists
}


SET LISTJOBS=Totvs_Job_Master Totvs_Job_Slv01 Totvs_Job_Slv02 Totvs_Job_Slv03
SET LISTMASTER=Totvs_Master

:: Adiciona os 20 Slaves à lista do Master
FOR /L %%I IN (1,1,20) DO CALL :AddListMaster %%I

SET LISTLIC=TotvsLicenseServer
SET LISTADT=DBAUDIT DBAccess64_AUDIT 
SET LISTDBA=DBAccess64_Totvs11 
SET LISTTSS=DBAccess64 appserver_0101_MDFe appserver_0103_MDFe Totvs11_TSS

:: Adiciona os serviços de TSS e TSSNFSE das 8 filiais
FOR /L %%I IN (1,1,8) DO CALL :AddListTSS %%I


SET LISTPRT=TOTVS11_PRT_Master TOTVS11_PRT_SLV1 TOTVS11_PRT_SLV2 TOTVS11_PRT_SLV3 TOTVS11_PRT_Comp
SET LISTPRTDB=DBAccess64_PRT


SET LISTA=0

IF "%1" NEQ "" SET LISTA=%1

IF %LISTA% EQU 0 (
	ECHO =================================
	ECHO LISTA DE SERVICOS:
	ECHO =================================
	ECHO.
	ECHO 1 - Somente Jobs
	ECHO 2 - Master e Slaves
	ECHO 3 - Licence Server e DbAccess
	ECHO 4 - TSS
	ECHO 5 - Todos [Exceto TSS]
	ECHO 6 - Todos [Com TSS]
	ECHO 7 - Prototipo
	ECHO.
	SET /P LISTA="Escolha a Lista de Servicos: "
	ECHO.
)

IF %LISTA% EQU 1 ( 

	SET LISTADSC=1 - Somente Jobs
	SET SERVER_SEL[1,1]=%SRVJOB%
	SET SERVER_SEL[1,2]=%LISTJOBS%
	
) ELSE IF %LISTA% EQU 2 (

	SET LISTADSC=2 - Master e Slaves
	SET SERVER_SEL[1,1]=%SRVAPP%
	SET SERVER_SEL[1,2]=%LISTMASTER%
	
) ELSE IF %LISTA% EQU 3 (

	SET LISTADSC=3 - Licence Server e DbAccess
	SET SERVER_SEL[1,1]=%SRVLIC%
	SET SERVER_SEL[1,2]=%LISTLIC%
	SET SERVER_SEL[1,3]=5
	SET SERVER_SEL[2,1]=%SRVADT%
	SET SERVER_SEL[2,2]=%LISTADT%
	SET SERVER_SEL[3,1]=%SRVDBA%
	SET SERVER_SEL[3,2]=%LISTDBA%
	
) ELSE IF %LISTA% EQU 4 (

	SET LISTADSC=4 - TSS
	SET SERVER_SEL[1,1]=%SRVTSS%
	SET SERVER_SEL[1,2]=%LISTTSS%
	
) ELSE IF %LISTA% EQU 5 (

	SET LISTADSC=5 - Todos - Exceto TSS
	SET SERVER_SEL[1,1]=%SRVLIC%
	SET SERVER_SEL[1,2]=%LISTLIC%
	SET SERVER_SEL[1,3]=5
	SET SERVER_SEL[2,1]=%SRVADT%
	SET SERVER_SEL[2,2]=%LISTADT%	
	SET SERVER_SEL[3,1]=%SRVDBA%
	SET SERVER_SEL[3,2]=%LISTDBA%
	SET SERVER_SEL[4,1]=%SRVAPP%
	SET SERVER_SEL[4,2]=%LISTMASTER%
	SET SERVER_SEL[5,1]=%SRVJOB%
	SET SERVER_SEL[5,2]=%LISTJOBS%
	
) ELSE IF %LISTA% EQU 6 (

	SET LISTADSC=6 - Todos - Com TSS
	SET SERVER_SEL[1,1]=%SRVLIC%
	SET SERVER_SEL[1,2]=%LISTLIC%
	SET SERVER_SEL[1,3]=5
	SET SERVER_SEL[2,1]=%SRVADT%
	SET SERVER_SEL[2,2]=%LISTADT%
	SET SERVER_SEL[3,1]=%SRVDBA%
	SET SERVER_SEL[3,2]=%LISTDBA%
	SET SERVER_SEL[4,1]=%SRVAPP%
	SET SERVER_SEL[4,2]=%LISTMASTER%
	SET SERVER_SEL[5,1]=%SRVTSS%
	SET SERVER_SEL[5,2]=%LISTTSS%
	SET SERVER_SEL[6,1]=%SRVJOB%
	SET SERVER_SEL[6,2]=%LISTJOBS%	
	
) ELSE IF %LISTA% EQU 7 (

	SET LISTADSC=7 - Prototipo
	SET SERVER_SEL[1,1]=%SRVPRT%
	SET SERVER_SEL[1,2]=%LISTPRTDB%
	SET SERVER_SEL[2,1]=%SRVPRT%
	SET SERVER_SEL[2,2]=%LISTPRT%



}